#host: '127.0.0.1'
#port: 8849
#namespace: '62c03b7b-2483-4a3d-9d3d-d3840d004292'
#user: 'nacos'
#password: 'nacos'
#dataid: 'userop_srv'
#group: 'dev'

host: '127.0.0.1'
port: 8848
namespace: "8d41ada1-5ac4-4ba8-bf10-8e64df3f81dc"
user: "nacos"
password: "nacos"
dataid: "userop_srv.json"
group: "dev"