# 启动编译环境
FROM golang:1.15-alpine AS builder

# 配置编译环境
RUN go env -w GO111MODULE=on
RUN go env -w GOPROXY=https://goproxy.cn,direct

# 拷贝源代码到镜像中
 

# 编译
 

FROM alpine:3.13
 
ENV ADDR=:8080

# 申明暴露的端口
EXPOSE 8080

# 设置服务入口

